.TH "StbDjVuLground" 1 1.5 "5 Jan 2023" "User Manual"

.SH NAME
stbdjvulground

.SH DESCRIPTION
DjVu Layered - image bundle on the mask + foreground + background using "Multi-scale binarization".

This utility splits an image into BG and FG according to an existing mask. It is possible to correct the mask.

.SH SYNOPSIS
stbdjvulground [options] image_in bw_mask_in [bg_out.png] [fg_out.png]

.SH OPTIONS
.TP
-b NUM
downsample FG and BG (default 3)
.TP
-l NUM
level of scale blocks (default 0 = auto)
.TP
-o N.N
part of overlay blocks (default 0.5)
.TP
-r
rewrite maks
.TP
-h
show this help message and exit

.SH EXAMPLE
stbdjvulground lena.png lena.mask.png lena.bg.png lena.fg.png 
 
 Load: lena.png
 image: 256x256:3
 Load: lena.mask.png
 mask: 256x256:3
 BG,FG: 86x86:3
 DjVuL ground... 7 level
 Save png: none, lena.bg.png, lena.fg.png.


.SH COPYRIGHT
This is free and unencumbered software released into the public domain.

.SH SEE ALSO
cjb2(1), c44(1), djvuextract(1), djvumake(1), stbdjvul(1)

.SH CONTACTS
Website: https://github.com/ImageProcessing-ElectronicPublications/stb-image-djvul
