.TH "StbDjVuL" 1 1.8 "11 Jan 2023" "User Manual"

.SH NAME
stbdjvul

.SH DESCRIPTION
DjVu Layered - image bundle on the mask + foreground + background using "Multi-scale binarization".

Degradation of images on layers mask, foreground and background by cluster analysis with a gradual decrease in block size.

This utility includes a mode for splitting an image into a BG and a FG based on an existing mask (ground). The mask can be corrected.
This utility includes a mode for reconstruct an image on an existing mask, BG and FG (reconstruct).

.SH SYNOPSIS
stbdjvul [options] image_in bw_mask_out.png [bg_out.png] [fg_out.png]

.SH OPTIONS
.TP
-a N.N
factor anisortopic (regulator, default 0.0 [off])
.TP
-b NUM
downsample FG and BG (default 3)
.TP
-c N.N
factor contrast (regulator, default 0.0 [off])
.TP
-d N.N
factor delta (regulator, default 0.0 [off])
.TP
-e N.N
factor FG/BG scale (regulator, default 1.0 [off])
.TP
-f NUM
downsample FG (default 2)
.TP
-l NUM
level of scale blocks (default 0 = auto)
.TP
-m NUM
mode: 0 - threshold, 1 - ground, 2 - recontruct (default 0)
.TP
-o N.N
part of overlay blocks (default 0.5)
.TP
-r
rewrite maks in ground mode
.TP
-w
white/black mode (default 1 = white)
.TP
-h
show this help message and exit

.SH EXAMPLE
 stbdjvul lena.png lena.mask.png lena.bg.png lena.fg.png

  Load: lena.png
  image: 256x256:3
  BG: 86x86:3
  FG: 43x43:3
  DjVuL... 7 level
  Save png: lena.mask.png, lena.bg.png, lena.fg.png.

 stbdjvul -m 1 -r lena.png lena.mask.png lena.bg.png lena.fg.png

  Load: lena.png
  image: 256x256:3
  Load: lena.mask.png
  mask: 256x256:3
  BG: 86x86:3
  FG: 43x43:3
  DjVuL ground... 7 level
  Save png: lena.mask.png, lena.bg.g.png, lena.fg.g.png.

 stbdjvul -m 2 lena.r.png lena.mask.png lena.bg.png lena.fg.png

  Load: lena.mask.png
  mask: 256x256:3
  Load: lena.bg.png
  BG: 86x86:3
  Load: lena.fg.png
  FG: 43x43:3
  DjVuL reconstruct... 2 level
  Save png: lena.r.png.

.SH COPYRIGHT
This is free and unencumbered software released into the public domain.

.SH SEE ALSO
cjb2(1), c44(1), djvuextract(1), djvumake(1)

.SH CONTACTS
Website: https://github.com/ImageProcessing-ElectronicPublications/stb-image-djvul
